### ISSUE TITLE
import-time exception

### ISSUE THREAD

**Issue by macobo** [macobo/python-grader#17]
Import time exception handling is a bit woncky - if for example we stay stuck behind a `input()` wait and after resolving that an exception occurs, we aren't reporting that properly.

**Comment by macobo** [comment]
We now are reporting that properly and the error is visible from the trace. Example:

``` python
Exception in program:

Traceback (most recent call last):
  File "/usr/lib/python3.3/threading.py", line 639, in _bootstrap_inner
    self.run()
  File "/home/macobo/projects/python-grader/graderenv/lib/python3.3/site-packages/grader-0.0.1-py3.3.egg/grader/execution_base.py", line 111, in run
    self.module = import_module(self.module_name, "<tested-program>")
  File "/home/macobo/projects/python-grader/graderenv/lib/python3.3/site-packages/grader-0.0.1-py3.3.egg/grader/utils.py", line 16, in import_module
    module = loader.load_module(name)
  File "<frozen importlib._bootstrap>", line 586, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1023, in load_module
  File "<frozen importlib._bootstrap>", line 1004, in load_module
  File "<frozen importlib._bootstrap>", line 562, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 869, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "KT1_midateha_solution.py", line 38, in <module>
    print(mida_teha(n, lyh).capitalize() + '!')
  File "KT1_midateha_solution.py", line 24, in mida_teha
    raise AssertionError()
AssertionError


Exception in tester:

Traceback (most recent call last):
  File "/home/macobo/projects/python-grader/graderenv/lib/python3.3/site-packages/grader-0.0.1-py3.3.egg/grader/execution_base.py", line 161, in call_test_function
    test_function(module)
  File "/home/macobo/projects/python-grader/graderenv/lib/python3.3/site-packages/grader-0.0.1-py3.3.egg/grader/core.py", line 43, in wrapper
    result = test_function(module, *args, **kwargs)
  File "KT1_midateha_tester.py", line 39, in test_function
    assert hasattr(m, 'module'), "Programmi täitmine ei lõppenud. Failis ei tohiks olla üleliigseid input() käski"
AssertionError: Programmi täitmine ei lõppenud. Failis ei tohiks olla üleliigseid input() käski
```
